### ISSUE TITLE
Manjaro install steps

### ISSUE THREAD

**Issue by fabiomontefuscolo** [phpsci/phpsci-carray#28]
Hi,

These are the install steps to enable it on my machine. Does it make sense to have in the README?

```sh
sudo pacman -S openblas lapacke cblas
phpize
./configure
make
make install
cat > /etc/php/conf.d/carray.ini <<EOF
extension=carray
EOF
```

**Comment by henrique-borba** [comment]
@fabiomontefuscolo thank you, we sure can use it. Please submit the changes on https://github.com/phpsci/phpsci-carray/blob/master/docs/index.md instead of README because later all install steps will be moved to the docs.

Congratulations and thank you for figuring this out. I will close the issue for now and after your pull request I will link both
